### ISSUE TITLE
Missing lib/vendor files

### ISSUE THREAD

**Issue by pierre-pizzetta** [realtimedespatch/orderflow-magento-module#9]
Installing from tarball available on the project page (no composer here), I seem to be missing some files when I try to export an order from the order table:

2015-05-13T11:49:01+00:00 ERR (3): Warning: include(SixBySix\RealtimeDespatch\Api\Credentials.php): failed to open stream: No such file or directory  in /var/www/lib/Varien/Autoload.php on line 94
2015-05-13T11:49:01+00:00 ERR (3): Warning: include(): Failed opening 'SixBySix\RealtimeDespatch\Api\Credentials.php' for inclusion (include_path='/var/www/app/code/local:/var/www/app/code/community:/var/www/app/code/core:/var/www/lib:.:/usr/share/php:/usr/share/pear')  in /var/www/lib/Varien/Autoload.php on line 94

**Comment by ghost** [comment]
Hi @pierre-pizzetta 

I've just checked the tar ball, and the missing file in your exception is present as expected. Therefore, the exception above is usually due to the presence of an already extended Varien_Autoloader. 

Can you please let me know if you can find an occurrence of the Varien_Autoload class being extended anywhere else in your code base?

Additionally, can you let me know which version of PHP you are running, as the library requires namespace support. This was released in PHP 5.3.

Cheers

**Comment by pierre-pizzetta** [comment]
Hi @thomb2233 ,

Thanks for the quick reply, we did have another rewrite in app/code/local/Varien/Autoload.php that was taking precedence over the app/code/community/Varien/Autoload.php rewrite from magento-composer-autoload, so vendor wasn't loaded.
Any reason the vendor files can't be in /lib like other module usualy do and avoid rewriting Varien_Autoload? (I guess that's composer related).

**Comment by tom-6x6** [comment]
Hi @pierre-pizzetta 

Great to hear that you have discovered the issue. For packaged releases, this is definitely something I will take a look at. However, for users installing via composer, we will need to retain the Varien Autoload extension to ensure the vendors are loaded correctly.

I'll close this issue in the meantime.

Thanks

Tom
